sudo: false
language: python
python:
  - "3.6"
  - "3.5"
  - "3.7-dev"
env:
  - PYTHON_TYPE=native
  - PYTHON_TYPE=conda
matrix:
  exclude:
    - python: "3.7-dev"
      env: PYTHON_TYPE=conda
  allow_failures:
    - python: "3.7-dev"
cache:
  directories:
    - $HOME/miniconda
    - .eggs
install:
  - if [[ $PYTHON_TYPE = conda ]]; then bash build-tools/install-conda.sh; fi
  - source build-tools/activate-conda.sh
  - pip install pytest-cov pylint invoke
script:
  - invoke test --cover --verbose
after_success:
  - coverage xml
  - bash <(curl -s https://codecov.io/bash)
  - sonar-scanner
addons:
  sonarcloud:
    organization: lenskit
