sudo: false
language: python
python:
  - "3.6"
  - "3.5"
  - "3.7"
env:
  - PYTHON_TYPE=native
  - PYTHON_TYPE=conda
matrix:
branches:
  except:
    - /^(fix|feature)\/.*$/
    - gh-pages
cache:
  pip: true
  directories:
    - $HOME/miniconda
    - .eggs
    - ml-100k
install:
  - if [[ $PYTHON_TYPE = conda ]]; then bash build-tools/install-conda.sh; fi
  - source build-tools/activate-conda.sh
  - pip install coverage pylint invoke
  - pip install pandas scipy cython
  - bash build-tools/fetch-ml100k.sh
script:
  - python setup.py coverage
after_success:
  - coverage xml
  - bash <(curl -s https://codecov.io/bash)
jobs:
  include:
    - stage: deploy
      install:
        - pip install invoke sphinx pandas
        - npm install -g netlify-cli
      script:
        - python setup.py build_sphinx
        - netlify deploy -t $NETLIFY_TOKEN
      if: branch = master AND type = push
