sudo: false
language: python
python:
  - "3.6"
  - "3.5"
env:
  - PYTHON_TYPE=native
  - PYTHON_TYPE=conda
install:
  - if [[ $PYTHON_TYPE = conda ]]; then bash build-tools/install-conda.sh; fi
  - source build-tools/activate-conda.sh
  - pip install coverage
script:
  - python setup.py coverage
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - sonar-scanner
addons:
  sonarcloud:
    organization: lenskit
